Imports System.Net.Mail
Module Mail

    ' The Email feature here. Using Gmail

    Public Sub Mailman()

        Dim ICSMail As New MailMessage()
        Dim MailGoogl As New SmtpClient("smtp.gmail.com")
        Dim SalesReportLog As System.Net.Mail.Attachment

        ICSMail.From = New MailAddress("Earlshawboss@gmail.com", "ICS Admin")
        ICSMail.[To].Add(FormMailLog.ManagerAdd)
        ICSMail.Subject = "Sales Report Log"
        ICSMail.Body = "Kindly find attached." & Environment.NewLine & " This message is autogenerated by UKZN ICS Tech Store."
        SalesReportLog = New System.Net.Mail.Attachment(System.Environment.CurrentDirectory.ToString & "\DailyLog.txt")
        ICSMail.Attachments.Add(SalesReportLog)
        MailGoogl.Port = 587
        MailGoogl.Credentials = New System.Net.NetworkCredential("Earlshawboss@gmail.com", "istn2ipproj")
        MailGoogl.EnableSsl = True

        Try
            MailGoogl.Send(ICSMail)
            FormMailLog.ProgBar = 1
        Catch ex As Exception
            FormMailLog.ProgBar = 0
            MsgBox(ex.Message)
        End Try

        If FormMailLog.ProgBar = 1 Then
            FormMailLog.Label2.Visible = True
            FormMailLog.Label2.Text = "Log sent successfully"
            FormMailLog.Button3.Enabled = True
            FormMailLog.Button3.Text = "Send"
            FormMailLog.TextBox1.Enabled = True

        ElseIf FormMailLog.ProgBar = 0 Then
            FormMailLog.Label2.Visible = True
            FormMailLog.Label2.Text = "Log could not be delivered"
            FormMailLog.Button3.Enabled = True
            FormMailLog.Button3.Text = "Send"
            FormMailLog.TextBox1.Enabled = True
        End If
    End Sub

End Module
