# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Enable .NET Framework 3.5
      run: |
        DISM /Online /Enable-Feature /FeatureName:NetFx3 /All
    - name: Restore dependencies
      run: dotnet restore ./ICSTechStore/ICSTechStore.vbproj
    - name: Build
      run: dotnet build ./ICSTechStore/ICSTechStore.vbproj --no-restore
    - name: Test
      run: dotnet test ./ICSTechStore/ICSTechStore.vbproj --no-build --verbosity normal
